server:
  port: 8082
  servlet:
    context-path: /PhoneBook

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: PHONE_BOOK
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PHONE_BBOK
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
